name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # Add your build and test commands here
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
          docker run --rm ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG npm test

  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

      - name: Deploy to Production
        run: |
          # Add your deployment commands here
          # This could be deploying to a Kubernetes cluster, cloud platform, etc.
