stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "registry.gitlab.com/dev-ops-group-x/flight-booking/airline_system"
  DOCKER_IMAGE_TAG: "1.0"

before_script:
  - echo "Install Docker..."
  - apt-get update -qy
  - apt-get install -y docker.io

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f "C:/Users/owner/Desktop/DevOps assignment/Airline/Dockerfile" .

deploy:
  stage: deploy
  script:
    - echo "Logging in to GitLab Container Registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
